name: deploy

on: 
  push:
    branches: 
      - main

jobs: 
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: Deploy
        uses: mdelillo/ssh-server-action@v1
        with:
          ngrok-authtoken: "2g4qIH3ScRR7ULIyd5qcFAyQxeW_7AzVV64wQMATAwuRPPKMz"
          ssh-public-key: "rsa-key-20240512"



