name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:

      - name: Wait for ngrok tunnel to be established.
        run: sleep 5

      - name: Get ngrok public URL
        id: ngrok
        run: echo "::set-output name=url::$(curl -sS http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')"

      - name: Deploy notifications.html
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            curl -X POST -H "Content-Type: application/json" -d '{"url": "${{ steps.ngrok.outputs.url }}"}' http://localhost:3000/webhook/update_data
