name: CI

on:
  push:
    branches: 
      - main

jobs:
  format-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: SetupPython 
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.5' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Run
        run: python webhook.py

      - name: autoCommit
        uses: stefanzweifel/git-auto-commit-action@v5