name: CI

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: SetupPython 
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.5' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python webhook.py &
          
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: mdelillo/ssh-server-action@v1
        with:
          ngrok-authtoken: ${{ secrets.NGROK_AUTH_TOKEN }}
          ssh-public-key: ""

      - name: Guardar estado
        run: echo "{nombre}={ secrets.NAME }" >> $GITHUB_STATE

      - name: Establecer salida
        run: echo "{nombre}={ secrets.NAME }" >> $GITHUB_OUTPUT