name: CI

on:
  push:
    branches: 
      - main

jobs:
  format-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name:
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.5' 
      - run: python webhook.py

      - name: Run
        uses: stefanzweifel/git-auto-commit-action@v5