# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: 
      - main

jobs:
  build-and-deploy:
    runs-on: xubuntu-latest
    steps:
      - name: Install packages
        run: npm ci

      - name: Bundle
        run: npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with: 
          branch: main
          folder: distq
